CREATE SEQUENCE SEQ_BOARD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPLY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE BOARD (
  BOARD_ID       NUMBER        DEFAULT SEQ_BOARD.NEXTVAL NOT NULL,
  BOARD_TITLE    VARCHAR2(200) NOT NULL,
  BOARD_CONTENT  VARCHAR2(4000) NOT NULL,
  CREATE_DATE    DATE          DEFAULT SYSDATE NOT NULL,
  MODIFY_DATE    DATE          NULL,
  DELETE_DATE    DATE          NULL,
  VIEW_COUNT     NUMBER        DEFAULT 0 NOT NULL,
  STOCK_ID       VARCHAR2(10)  NULL,
  BOARD_TYPE     VARCHAR2(10)  DEFAULT 'FREE' NOT NULL,
  USER_ID        VARCHAR2(20)  NOT NULL,
  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_ID),
  CONSTRAINT CK_BOARD_TYPE CHECK (BOARD_TYPE IN ('STOCK','FREE')),
  CONSTRAINT CK_BOARD_STOCK CHECK (
    (BOARD_TYPE = 'FREE'  AND STOCK_ID IS NULL) OR
    (BOARD_TYPE = 'STOCK' AND STOCK_ID IS NOT NULL)
  )
);

COMMENT ON COLUMN BOARD.BOARD_ID IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성 날짜';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '게시글이 마지막으로 수정된 일자';
COMMENT ON COLUMN BOARD.DELETE_DATE IS '게시글 삭제 시 일자(소프트 삭제)';
COMMENT ON COLUMN BOARD.VIEW_COUNT IS '해당 게시글 조회수';
COMMENT ON COLUMN BOARD.STOCK_ID IS '종목 게시판인 경우 종목코드(자유 게시판은 NULL)';
COMMENT ON COLUMN BOARD.BOARD_TYPE IS '게시판 타입(STOCK/FREE)';
COMMENT ON COLUMN BOARD.USER_ID IS '작성자 아이디';

CREATE INDEX IX_BOARD_TYPE_DATE ON BOARD (BOARD_TYPE, CREATE_DATE DESC);
CREATE INDEX IX_BOARD_STOCK_ID ON BOARD (STOCK_ID);

CREATE TABLE REPLY (
  REPLY_ID       NUMBER        DEFAULT SEQ_REPLY.NEXTVAL NOT NULL,
  REPLY_CONTENT  VARCHAR2(2000) NOT NULL,
  CREATE_DATE    DATE          DEFAULT SYSDATE NOT NULL,
  BOARD_ID       NUMBER        NOT NULL,
  USER_ID        VARCHAR2(20)  NOT NULL,
  DELETE_DATE    DATE          NULL,
  MODIFY_DATE    DATE          NULL,
  CONSTRAINT PK_REPLY PRIMARY KEY (REPLY_ID),
  CONSTRAINT FK_REPLY_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID)
);

COMMENT ON COLUMN REPLY.REPLY_ID IS '댓글 번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '작성 날짜';
COMMENT ON COLUMN REPLY.BOARD_ID IS '게시글 번호';
COMMENT ON COLUMN REPLY.USER_ID IS '댓글 작성자 아이디';
COMMENT ON COLUMN REPLY.DELETE_DATE IS '댓글 삭제 시 일자(소프트 삭제)';
COMMENT ON COLUMN REPLY.MODIFY_DATE IS '댓글이 마지막으로 수정된 일자';

CREATE INDEX IX_REPLY_BOARD_DATE ON REPLY (BOARD_ID, CREATE_DATE ASC);