spring.application.name=doyouknowju

# 서버 포트번호 변경
# server.port=8888

# 설정영역

# contextRoot 설정
server.servlet.context-path=/dykj

# 파일 업로드를 위한 MultipartResolver 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 마이바티스 설정
# 데이터베이스 접속 정보 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=DYKJ
spring.datasource.password=DYKJ

# mybatis-config에 작성하던 settings들을 이곳에 작성
mybatis.configuration.jdbc-type-for-null=NULL

# mapper 파일 경로
mybatis.mapper-locations=/mappers/*.xml

# Carmel 표기법 _ 처리 자동
mybatis.configuration.map-underscore-to-camel-case=true

# 별칭 설정 (하위 패키지 설정)
mybatis.type-aliases-package=com.project.dykj


# 파일 업로드 경로 작성 - 별도의 파일 경로를 작성하여 해당 위치에 업로드 처리할 것


# JWT 관련 설정
# JWT 토큰 서명에 사용할 비밀 키(최소 32바이트) (실제 운영환경에서는 더 복잡하고 안전한 키 사용)
jwt.secret=faddfadfdfas.bebebberasdfsa.basosspodkdvvfdbaafbdwe3t3t2

# JWT 토큰 만료 시간 (밀리초 단위 설정)
jwt.expiration=864000000


# log4j 설정 (slf4j)
# 로그 레벨 설정 (기본레벨)
logging.level.root=info

# 패키지별 설정 또는 클래스 별 설정